filename: '63762BB'
input_dir: 'input'
dataset: 'dataset'
w_sfr: 50
result: 'result'
lr_I: 1e-3
lr_II: 2e-3
epochs_I: 501
epochs_II: 501
BS: 24
noise: shot0.00
h5: 54854_rgb.h5
loss: l1
net: ss
fov1: 5
fov2: 20
npy: './dataset/63762BB/npy'